name: Compile and Assemble

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches:
      - "main"
  pull_request:


jobs:
  build:

    runs-on: ${{ matrix.os }}
    permissions:
      contents: read

    strategy:
      matrix:
        os: [ ubuntu-latest ]

    steps:
      - name: Configure Git
        run: |
          git config --global core.autocrlf input
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'

      # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Check Compilation
        run: ./gradlew compileKotlin compileTestKotlin --no-parallel

      - name: Assemble
        run: ./gradlew assemble --no-parallel

      - name: Collect reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reports-${{ matrix.os }}
          path: |
            **/build/reports/
